#!/bin/bash
#############################
# зависимости:
# media-sound/shntool
# app-cdr/cuetools
# media-libs/flac
# media-sound/mac
# media-sound/ttaenc
# media-sound/wavpack
# iconv
#
#############################

if [ "${1}" == '' ]; then
shellDir="$PWD"
else
shellDir="${1}"
fi

if [ "${2}" == '' ]; then
sourceEncoding="cp1251"
else
sourceEncoding="$2"
fi

rename_files() {
   file_cue=$1
   for (( i=1 ; i <= $(cueprint -d '%N' "${file_cue}") ; ++i ))
   do
       NN=$(printf 'split-track%02d' $i)
       [ -s "$NN.flac" ] && {
          cueprint -n $i -t \
          'ARRANGER=%A\nCOMPOSER=%C\nGENRE=%G\nMESSAGE=%M\nTRACKNUMBER=%n\nARTIST=%p\nTITLE=%t\nALBUM=%T\n' \
          "${file_cue}" | egrep -v '=$' | iconv -f "${sourceEncoding}" -t utf-8 | metaflac --import-tags-from=- $NN.flac
          out_name=$(cueprint -n $i -t "%p - %t" "${file_cue}" | iconv -f "${sourceEncoding}" -t utf-8 |  sed -e "s,/,,g")
          if [ -f "${out_name}.flac" ]; then
            out_name=$NN
          fi
          mv $NN.flac "${out_name}.flac"
          echo "processed file \"${out_name}.flac\""
       }
    done
}

find "${shellDir}" -name '*.cue' -print | while read file_cue; do
    file_flac=$(basename "${file_cue}" | sed "s/.cue/.flac/g")
    file_flac=$(dirname "${file_cue}")"/${file_flac}"
    if [ ! -f "$file_flac" ]; then
        echo "file ${file_flac} does not exists"
        continue
    fi
    dir=$(dirname "${file_cue}")
    pushd "${dir}"
    cuebreakpoints "$file_cue" | shnsplit -o flac "$file_flac"
    rename_files "${file_cue}"
    rm -f "${file_cue}" "${file_flac}"
    popd
done


#while read cuefile
#do
# cue="${cuefile##*/}"
# obj=${cue%.cue}
# objdir="${cuefile%/*}"
# pushd "$objdir"

# if [ -f "$obj".flac ]; then
# shntool split -i "flac" -o "flac" -f "$cue" -t %n "$obj".flac \
# || echo "Не удалось разделить $obj.flac" \
# exit 1
# elif [ -f "$obj".ape ]; then
# shntool split -i "ape" -o "flac" -f "$cue" -t %n "$obj".ape \
# || echo "Не удалось разделить $obj.ape" \
# exit 1
# elif [ -f "$obj".tta ]; then
# shntool split -i "tta" -o "flac" -f "$cue" -t %n "$obj".tta \
# || echo "Не удалось разделить $obj.tta" \
# exit 1
# elif [ -f "$obj".wv ]; then
# shntool split -i "wv" -o "flac" -f "$cue" -t %n "$obj".wv \
# || echo "Не удалось разделить $obj.wv" \
# exit 1
# else
# echo "Файл $obj не найден, выходим."
# exit 1
# fi
#    done < <(find . -type f -iname "*.cue")
